import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Aurora from "@/components/ui/Aurora";
import Particles from "@/components/ui/Particles";
import Header from "@/components/Header";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spotify = localFont({
  src:'./fonts/SpotifyMix-Bold.woff2',
  weight: '100 900'
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spotify.className} antialiased bg-black`}
      >
        <div className="relative min-h-screen font-spotify">
          <div className="fixed inset-0 z-0">
            <Aurora
              colorStops={["#3A29FF", "#FF94B4", "#FF3232"]}
              blend={0.9}
              amplitude={0.3}
              speed={0.6}
            />
          </div>
          <div className="relative z-10">
            <Header/>
            {children}
            </div>
        </div>
      </body>
    </html>
  );
}
